import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { ThemeProvider } from "styled-components";
import { GlobalStyles, theme, themeDark } from "../constants/theme";
import Campaign from "../containers/Campaign";
import { useLayout } from "../context/LayoutProvider";

const Home: NextPage = () => {
  const { isDark } = useLayout();
  return (
    <div>
      <Head>
        <title>Unity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={isDark ? theme : themeDark}>
        <GlobalStyles />
        <Campaign />
      </ThemeProvider>
    </div>
  );
};

export default Home;
